In [1]:
import numpy as np
import pandas as pd

### 01.Create DataFrame
##### 01 - From Dictionary
##### 02 - From List of Dicts
##### 03 - From List of List

In [2]:
# 01 - From Dictionary - Specify values to columns
df = pd.DataFrame({"col1":[1,2,3],"col2":[2,3,4],"col3":[3,4,5]}, index=[3,4,5])

# 02 - From List of Dicts - Specify values to column one by one 
df = pd.DataFrame([{"a":1, "b":3, "c":3},{"a":1, "b":3, "c":3}, {"a":4, "b":5, "c":6}], index=[5,6,7])

# 03 - From List of Lists - Specify values to column
df = pd.DataFrame([[11,12,13],
                   [14,15,16],
                   [17,18,19]],
                   columns = ["ColumnA","ColumnB","ColumnC"],
                   index = [1,2,3])

### 02.Read & Write

In [72]:
# Read
coffee = pd.read_csv("./data/coffee.csv")
olym = pd.read_excel("./data/olympics-data.xlsx", sheet_name="results")
bios = pd.read_csv("./data/bios.csv")
nocs = pd.read_csv('./data/noc_regions.csv')

# Write
df.to_csv("path/filename.csv")
df.to_excel("path/filename.xlsx")

In [ ]:
# display(coffee.head(10))
# display(olym.head(10))

### 03.Data Exploration

In [5]:
df.head()              # First 5 rows   --> Pandas DF
df.tail()              # Last 5 rows    --> Pandas DF
df.shape               # (rows, columns)--> Tuple
df.info()              # Summary info   --> NoneType
df.describe()          # Statistics for numeric columns --> Pandas DF
df.columns             # Column names
df.index               # Index info
df.dtypes              # Data types                --> Pandas Series
df['col1'].value_counts()  # Count unique values   --> Numpy Array
df['col1'].unique()        # Unique values         --> Numpy Array

### 04.Selection
#### Loc: Allow us to access row/column through dataFrame label, e.g. coffee.loc[#Rows, #Cols]
#### iloc: Allow us to access row/column through dataFrame index only!

In [6]:
coffee["Day"]                             # Single column
coffee[["Day", "Coffee Type"]]            # Multilple columns

coffee.iloc[0]                            # Single row
coffee.iloc[[0,1,2]]                      # Multilple rows

coffee.loc[0:3, ['Day','Units Sold']]     # loc Slicing to select columns and rows
coffee.iloc[0:3, [1,2]]                   # iloc Slicing to select columns and rows

  Coffee Type  Units Sold
0    Espresso          25
1       Latte          15
2    Espresso          30

### 05.Filtering
##### 01 - Numerical Values
##### 02 - Multiple filtering criterion
##### 03 - Filtering data | string operation, regular expression
##### 04 - Filtering data | Query

In [7]:
# 01 - Numerical Values¶
coffee[coffee['Units Sold']>20][["Day","Coffee Type"]]
coffee.loc[coffee['Units Sold']>20, ["Day","Coffee Type"]]

# 02 - Multiple filtering criterion¶
coffee[(coffee["Units Sold"]>20) & (coffee["Day"].isin(["Monday","Tuesday"]))]

# 03 - Filtering data | string operation, regular expression (Contains, isin, startswith)
coffee[coffee["Coffee Type"].str.contains("Espr", case=False)]   # contains
coffee[coffee["Coffee Type"].str.startswith("Espr")]             # startswith
coffee[coffee["Day"].isin(["Monday","Tuesday"])]                 # isin

# 04 - Filtering data | Query
coffee.query("Day == 'Monday' and `Coffee Type` == 'Latte'" )
coffee.query("Day == 'Monday' and `Units Sold` >= 25" )

      Day Coffee Type  Units Sold
0  Monday    Espresso          25

### 06.Add/Delete/Modify Columns
##### 01 - Rename columns
##### 02 - Add/Drop Columns (Basic)
##### 03 - Add/Drop Columns (String & Datetime Operations)
##### 04 - Adding/Removing Columns | Using Lambda, Custom Function w/ .apply()

In [69]:
# 01 - Rename columns
coffee.rename(columns={"Day":"Day_new","Coffee Type":"Coffee_Type"})

# 02 - Add/Drop Columns (Basic)
coffee["Total Price"] = 4.5*coffee["Units Sold"]
coffee.drop(columns = ["Total Price"], inplace=True)

# 03 - Add/Drop Columns (String & Datetime Operations)
bios['First Name'] = bios['name'].str.split(' ').str[0]     # split
bios['Born Datetime'] = pd.to_datetime(bios['born_date'], format="%Y-%m-%d")   #pd.to_datetime
bios['Born_year'] = bios['Born Datetime'].dt.year                              # year part
bios['Born_month'] = bios['Born Datetime'].dt.month                            # month part

# 04 - Adding/Removing Columns | Using Lambda, Custom Function w/ .apply()
bios['Hieght_category'] = bios["height_cm"].apply(lambda x: "tall" if x > 180 else ("short" if x < 170 else "avg"))

def Height_categorizer(row, var):
    if row[var] > 180:
        return "tall"
    elif row[var] >= 170:
        return "avg"
    else:
        return "short"
bios['Hieght_category2'] = bios.apply(lambda row: Height_categorizer(row, var="height_cm"), axis=1)

### 07.Sorting by specific columns in ascending/descending columns

In [138]:
bios_sorted = bios.sort_values(["born_region","born_city"], ascending=[0,1])

### 08.Reshape Data
##### 01 - Melt (Gather columns into rows, like ae -> suppae)
##### 02 - Pivot(Gather rows into columns, like suppae to ae)
##### 03 - concat Vertically (Append rows)
##### 04 - concat Horizontally (Append columnes)
##### 05 - Merge (Like Join)

In [134]:
df1 = pd.DataFrame(
    [{"usubjid":"001", "QNAM":"AENO1", "VAL":"Discontinued"},
     {"usubjid":"002", "QNAM":"AENO1", "VAL":"Discontinued2"},
     {"usubjid":"001", "QNAM":"AENO2", "VAL":"Dead1"},
     {"usubjid":"002", "QNAM":"AENO2", "VAL":"Dead2"}]
)
df2 = pd.DataFrame(
    [{"usubjid":"003", "QNAM":"AENO1", "VAL":"Discontinued"},
     {"usubjid":"004", "QNAM":"AENO1", "VAL":"Discontinued2"},
     {"usubjid":"003", "QNAM":"AENO2", "VAL":"Dead1"},
     {"usubjid":"004", "QNAM":"AENO2", "VAL":"Dead2"}]
)

df3 = pd.DataFrame({"usubjid":["001","002","003","004","005"], "name":["Lily","Tom","Amy","Henry","Sophia"]})

In [132]:
# 03 - concat Vertically (Append rows)
df_concat_ver = pd.concat([df1,df2], axis=0)

# 04 - concat Horizontally (Append columnes)
df_concat_hor = pd.concat([df1,df2], axis=1)

# 02 - Pivot(Gather rows into columns, like suppae to ae)
df_pivot = pd.pivot(df_concat_ver, columns="QNAM", values="VAL", index="usubjid").reset_index()

# 01 - Melt (Gather columns into rows, like ae -> suppae)
df_melt = pd.melt(df_pivot, id_vars=["usubjid"], value_vars=["AENO1","AENO2"], var_name="QNAM", value_name="value")


# 05 - Merge (Like Join)
df_merge_left  = pd.merge(df3, df_pivot, how='left', on="usubjid")   
df_merge_right = pd.merge(df3, df_pivot, how='right', on="usubjid") 
df_merge_inner = pd.merge(df3, df_pivot, how='inner', on="usubjid") 
df_merge_outer = pd.merge(df3, df_pivot, how='outer', on="usubjid")

  usubjid    name          AENO1  AENO2
0     001    Lily   Discontinued  Dead1
1     002     Tom  Discontinued2  Dead2
2     003     Amy   Discontinued  Dead1
3     004   Henry  Discontinued2  Dead2
4     005  Sophia            NaN    NaN

### 09.Handle Missing Values
##### 01 - find rows with missing
##### 02 - Drop rows with NA
##### 03 - Fill NA with values

In [173]:
coffee = pd.read_csv('./data/coffee.csv')
coffee.loc[[2,3], ['Units Sold']] = np.nan

# 01 - Find Missing 
coffee.isna().sum()  # Count missing
coffee["Units Sold"].isna().sum()   # find rows with (a specific column is/isn't na)  ---- .isna()/.notna()
coffee["Units Sold"].notna().sum()  # find rows with (a specific column is/isn't na)  ---- .isna()/.notna()

# 02 - Drop Missing 
coffee2 = coffee.dropna()     # drop rows with NA
coffee.dropna(subset=["Units Sold"])  # drop rows with specific column(s) as NA


# 03 - Fill NA with values
coffee['Units Sold_new'] = coffee['Units Sold'].fillna(coffee['Units Sold'].mean())

### 09 - Aggregating Data 
##### 01 - Using Groupby - groupby() .sum() .mean() .agg()
##### 02 - Aggregating Data | Pivot Tables (corresponding to 'proc transpose' in SAS)

In [187]:
coffee["Units Sold"] = coffee["Units Sold"].fillna(coffee["Units Sold"].mean())
coffee["Total"] = 4.5*coffee["Units Sold"]

In [191]:
# 01 - Using Groupby - groupby() .sum() .mean() .agg()
agg_data1 = coffee.groupby(["Day", "Coffee Type"])["Units Sold"].sum().reset_index()
agg_data2 = coffee.groupby(["Day", "Coffee Type"]).agg({"Units Sold":["mean","sum"], "Total":["mean","max"]}).reset_index()


# 02 - Aggregating Data | Pivot Tables (corresponding to 'proc transpose' in SAS)
coffee.pivot_table(columns=["Coffee Type"], index=["Day"], values="Total", aggfunc=["sum","mean"])

                 sum             mean
Coffee Type Espresso   Latte Espresso   Latte
Day
Friday        202.50  157.50   202.50  157.50
Monday        112.50   67.50   112.50   67.50
Saturday      202.50  157.50   202.50  157.50
Sunday        202.50  157.50   202.50  157.50
Thursday      180.00  135.00   180.00  135.00
Tuesday       153.75  153.75   153.75  153.75
Wednesday     157.50  112.50   157.50  112.50

### 10. Drop Duplicates

In [ ]:
customers.drop_duplicates(subset=['email'], inplace=True)